# ─────────────────────────────────────────────────────────────
# report_generator.py  —  FIXED VERSION
# Fixes:
#   1. Unicode chars (—, ✅, ❌ etc) cleaned before output
#   2. Deprecated ln= replaced with new_x/new_y
#   3. Uses fpdf2 modern API throughout
# ─────────────────────────────────────────────────────────────

from fpdf import FPDF, XPos, YPos
import os
from datetime import datetime


def clean_text(text):
    """
    Removes or replaces characters that Helvetica
    (latin-1) cannot encode.
    Covers em-dash, smart quotes, emojis, checkmarks etc.
    """
    if not text:
        return ""
    replacements = {
        "\u2014": "-",   # em dash
        "\u2013": "-",   # en dash
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2022": "*",   # bullet
        "\u2026": "...", # ellipsis
        "\u00a0": " ",   # non-breaking space
        "\u2265": ">=",  # >=
        "\u2264": "<=",  # <=
        "\u00e9": "e",   # é
        "\u00e0": "a",   # à
        "\u00fc": "u",   # ü
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)

    # Strip anything still outside latin-1 range
    result = ""
    for ch in text:
        try:
            ch.encode("latin-1")
            result += ch
        except (UnicodeEncodeError, UnicodeDecodeError):
            result += " "
    return result.strip()


class ATSReportPDF(FPDF):
    """Custom PDF with header and footer."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(37, 99, 235)
        self.cell(
            0, 10, "ResumeIQ",
            new_x=XPos.RIGHT, new_y=YPos.TOP
        )
        self.set_font("Helvetica", "", 9)
        self.set_text_color(107, 114, 128)
        self.cell(
            0, 10, "ATS Resume Analysis Report",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        self.ln(2)
        self.set_draw_color(229, 231, 235)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(156, 163, 175)
        self.cell(
            0, 10,
            f"Generated by ResumeIQ  |  "
            f"Page {self.page_no()}  |  "
            f"{datetime.now().strftime('%d %b %Y')}",
            align="C",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )


def generate_report(results, output_path):
    """
    Takes cleaned results dict and writes a PDF to
    output_path. Returns output_path on success.
    """

    pdf = ATSReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Helper functions ──────────────────────────────────────

    def section_title(text):
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(17, 24, 39)
        pdf.set_fill_color(239, 246, 255)
        pdf.cell(
            0, 8, f"  {clean_text(text)}",
            fill=True,
            new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        pdf.ln(3)

    def body_text(text, color=(55, 65, 81)):
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*color)
        pdf.multi_cell(0, 6, clean_text(text))
        pdf.ln(1)

    def key_value(key, value, value_color=None):
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(55, 65, 81)
        pdf.cell(
            55, 7, clean_text(key) + ":",
            new_x=XPos.RIGHT, new_y=YPos.TOP
        )
        pdf.set_font("Helvetica", "", 10)
        if value_color:
            pdf.set_text_color(*value_color)
        else:
            pdf.set_text_color(17, 24, 39)
        pdf.cell(
            0, 7, clean_text(str(value)),
            new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )

    def score_bar(label, score, color_rgb):
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(107, 114, 128)
        pdf.cell(
            55, 6, clean_text(label),
            new_x=XPos.RIGHT, new_y=YPos.TOP
        )
        x = pdf.get_x()
        y = pdf.get_y() + 1
        # Background
        pdf.set_fill_color(229, 231, 235)
        pdf.rect(x, y, 100, 4, style="F")
        # Fill
        fill_w = max(0, min(float(score), 100))
        if fill_w > 0:
            pdf.set_fill_color(*color_rgb)
            pdf.rect(x, y, fill_w, 4, style="F")
        # Pct text
        pdf.set_x(x + 103)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(
            20, 6, f"{score}%",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )

    def keyword_row(label, items, color_rgb):
        if not items:
            return
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(55, 65, 81)
        pdf.cell(
            0, 6, clean_text(label),
            new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*color_rgb)
        clean_items = [clean_text(str(i)) for i in items[:15]]
        text = "  " + "  |  ".join(clean_items)
        if len(items) > 15:
            text += f"  ... +{len(items)-15} more"
        pdf.multi_cell(0, 5, text)
        pdf.ln(2)

    # ── PAGE 1: Overview ──────────────────────────────────────

    # Report title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(
        0, 12, "ATS Compatibility Report",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT
    )

    resume_fn  = clean_text(
        results.get("resume_filename", "")
    )
    analysed   = clean_text(
        results.get("analysed_at", "")
    )
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(
        0, 6, f"Resume: {resume_fn}  |  {analysed}",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT
    )
    pdf.ln(5)

    # Big score
    score       = float(results.get("final_score", 0))
    score_label = clean_text(
        results.get("score_label", "")
    )
    if score >= 75:
        score_color = (22, 163, 74)
    elif score >= 50:
        score_color = (217, 119, 6)
    else:
        score_color = (220, 38, 38)

    pdf.set_font("Helvetica", "B", 44)
    pdf.set_text_color(*score_color)
    pdf.cell(
        80, 18, f"{int(score)}/100",
        new_x=XPos.RIGHT, new_y=YPos.TOP
    )
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0, 18, score_label,
        align="R",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT
    )
    pdf.ln(2)

    # Grade
    grade = clean_text(results.get("final_grade", ""))
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(55, 65, 81)
    pdf.cell(
        0, 7, grade,
        new_x=XPos.LMARGIN, new_y=YPos.NEXT
    )
    pdf.ln(3)

    # Score breakdown
    section_title("Score Breakdown")
    score_bar(
        "AI Semantic Match",
        results.get("semantic_score", 0),
        (124, 58, 237)
    )
    score_bar(
        "Keyword Match",
        results.get("keyword_score", 0),
        (37, 99, 235)
    )
    pdf.ln(3)

    # JD level
    jd_level   = clean_text(
        results.get("jd_level", "Unknown")
    )
    jd_warning = results.get("jd_warning")
    section_title("Job Description Analysis")
    key_value("Seniority Level", jd_level)
    if jd_warning:
        body_text(jd_warning, color=(146, 64, 14))
    pdf.ln(2)

    # Keyword analysis
    section_title("Keyword Analysis")
    key_value(
        "Matched keywords",
        str(results.get("matched_count", 0))
    )
    key_value(
        "Missing keywords",
        str(results.get("missing_count", 0))
    )
    pdf.ln(2)

    keyword_row(
        "Matched keywords:",
        results.get("matched_keywords", []),
        (22, 163, 74)
    )
    keyword_row(
        "Missing keywords:",
        results.get("missing_keywords", []),
        (220, 38, 38)
    )

    # Soft / synonym matches
    soft = results.get("soft_matches", [])
    if soft:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(55, 65, 81)
        pdf.cell(
            0, 6, "Smart synonym matches (AI detected):",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(124, 58, 237)
        for m in soft[:6]:
            rk  = clean_text(
                str(m.get("resume_keyword", ""))
            )
            jdk = clean_text(
                str(m.get("jd_keyword", ""))
            )
            sim = int(
                float(m.get("similarity", 0)) * 100
            )
            pdf.cell(
                0, 5,
                f"  '{rk}'  approx  '{jdk}'"
                f"  ({sim}% similar)",
                new_x=XPos.LMARGIN, new_y=YPos.NEXT
            )
        pdf.ln(2)

    # ── PAGE 2: Section scores + Suggestions ─────────────────
    pdf.add_page()

    sec_kw = results.get("section_keyword_scores", {})
    if sec_kw:
        section_title("Section-Level Scores")
        for sec_name, data in sec_kw.items():
            sc = float(data.get("score", 0))
            if sc >= 65:
                c = (22, 163, 74)
            elif sc >= 40:
                c = (217, 119, 6)
            else:
                c = (220, 38, 38)
            score_bar(sec_name.capitalize(), sc, c)
        pdf.ln(3)

    sec_report = results.get("section_report", {})
    if sec_report:
        section_title("Section Strength Report")
        for sec_name, info in sec_report.items():
            status = clean_text(
                info.get("status", "")
                if isinstance(info, dict) else ""
            )
            note = clean_text(
                info.get("note", "")
                if isinstance(info, dict) else str(info)
            )
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(55, 65, 81)
            pdf.cell(
                50, 6,
                clean_text(sec_name.upper()) + ":",
                new_x=XPos.RIGHT, new_y=YPos.TOP
            )
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(17, 24, 39)
            pdf.cell(
                0, 6, f"{status}  {note}",
                new_x=XPos.LMARGIN, new_y=YPos.NEXT
            )
        pdf.ln(3)

    suggestions = results.get("suggestions", [])
    if suggestions:
        section_title(
            f"Improvement Suggestions "
            f"({len(suggestions)} total)"
        )
        for i, s in enumerate(suggestions[:12], 1):
            clean_s = clean_text(str(s))
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(55, 65, 81)
            pdf.multi_cell(
                0, 6, f"  {i}. {clean_s}"
            )
            pdf.ln(1)
        pdf.ln(2)

    verb_verdict = results.get("verb_verdict", "")
    if verb_verdict:
        section_title("Action Verb Check")
        body_text(clean_text(verb_verdict))

    # Footer note
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(156, 163, 175)
    pdf.multi_cell(
        0, 5,
        "This report was generated by ResumeIQ - "
        "an AI-powered ATS resume analyzer built at "
        "MIT-ADT University, Pune. "
        "Scores are indicative and based on keyword "
        "and semantic similarity analysis."
    )

    pdf.output(output_path)
    return output_path


# ── Test ──────────────────────────────────────────────────────
if __name__ == "__main__":
    sample = {
        "final_score"    : 67.5,
        "semantic_score" : 71.2,
        "keyword_score"  : 63.8,
        "final_grade"    : "Average Match - needs improvement",
        "score_label"    : "Average Match",
        "resume_filename": "Anushka_Resume.pdf",
        "analysed_at"    : "10 Jun 2026, 09:21 PM",
        "jd_level"       : "Mid",
        "jd_warning"     : (
            "This JD requires 2-4 years experience. "
            "Highlight projects and certifications strongly."
        ),
        "matched_keywords": [
            "python", "sql", "git", "linux", "cybersecurity"
        ],
        "missing_keywords": [
            "flask", "docker", "pandas", "numpy",
            "machine learning"
        ],
        "matched_count"  : 5,
        "missing_count"  : 5,
        "soft_matches"   : [
            {
                "resume_keyword": "dsa",
                "jd_keyword"    : "data structures",
                "similarity"    : 0.73,
            }
        ],
        "section_report" : {
            "skills": {
                "status": "Good",
                "note"  : "189 chars",
                "length": 189,
            },
            "projects": {
                "status": "Good",
                "note"  : "445 chars",
                "length": 445,
            },
            "experience": {
                "status": "Missing",
                "note"  : "Not found - add one",
                "length": 0,
            },
        },
        "section_keyword_scores": {
            "skills"  : {"score": 78.0,
                         "matched": ["python", "sql"]},
            "projects": {"score": 55.0,
                         "matched": ["git"]},
        },
        "suggestions": [
            "Add flask to your Skills section",
            "Add docker to your Skills section",
            "Add an Experience section",
        ],
        "verb_verdict"       : "Good - no weak verbs found",
        "high_priority_count": 1,
    }

    out = generate_report(sample, "test_report.pdf")
    print(f"Report saved: {out}")
    print("Open test_report.pdf to check it looks correct.")